id: I2149979C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T12:40:55+00:00'
last_modified: '2022-06-07T12:02:44.281007+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD159529
  title: ཀྲུང་གོའི་བོད་རིག་པ།（རྒྱ་ཡིག་）
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    674B:
      image_group_id: I4PD4156
      title: Volume 1 of krung go'i bod rig pa/（rgya yig ）
      total_pages: 134
      order: 1
      base_file: 674B.txt
    F180:
      image_group_id: I4PD4157
      title: Volume 2 of krung go'i bod rig pa/（rgya yig ）
      total_pages: 178
      order: 2
      base_file: F180.txt
    6A4F:
      image_group_id: I4PD4158
      title: Volume 3 of krung go'i bod rig pa/（rgya yig ）
      total_pages: 182
      order: 3
      base_file: 6A4F.txt
    C98E:
      image_group_id: I4PD4159
      title: Volume 4 of krung go'i bod rig pa/（rgya yig ）
      total_pages: 134
      order: 4
      base_file: C98E.txt
    6E6A:
      image_group_id: I4PD4160
      title: Volume 5 of krung go'i bod rig pa/（rgya yig ）
      total_pages: 266
      order: 5
      base_file: 6E6A.txt
    0B33:
      image_group_id: I4PD4161
      title: Volume 6 of krung go'i bod rig pa/（rgya yig ）
      total_pages: 150
      order: 6
      base_file: 0B33.txt
    B601:
      image_group_id: I4PD4162
      title: Volume 7 of krung go'i bod rig pa/（rgya yig ）
      total_pages: 264
      order: 7
      base_file: B601.txt
    D369:
      image_group_id: I4PD4163
      title: Volume 8 of krung go'i bod rig pa/（rgya yig ）
      total_pages: 166
      order: 8
      base_file: D369.txt
    FC58:
      image_group_id: I4PD4164
      title: Volume 9 of krung go'i bod rig pa/（rgya yig ）
      total_pages: 264
      order: 9
      base_file: FC58.txt
    C705:
      image_group_id: I4PD4165
      title: Volume 10 of krung go'i bod rig pa/（rgya yig ）
      total_pages: 150
      order: 10
      base_file: C705.txt
    '3469':
      image_group_id: I4PD4166
      title: Volume 11 of krung go'i bod rig pa/（rgya yig ）
      total_pages: 264
      order: 11
      base_file: 3469.txt
    70FE:
      image_group_id: I4PD4167
      title: Volume 12 of krung go'i bod rig pa/（rgya yig ）
      total_pages: 150
      order: 12
      base_file: 70FE.txt
    '2218':
      image_group_id: I4PD4168
      title: Volume 13 of krung go'i bod rig pa/（rgya yig ）
      total_pages: 150
      order: 13
      base_file: 2218.txt
    A24B:
      image_group_id: I4PD4169
      title: Volume 14 of krung go'i bod rig pa/（rgya yig ）
      total_pages: 150
      order: 14
      base_file: A24B.txt
    B65D:
      image_group_id: I4PD4170
      title: Volume 15 of krung go'i bod rig pa/（rgya yig ）
      total_pages: 238
      order: 15
      base_file: B65D.txt
    9DD1:
      image_group_id: I4PD4171
      title: Volume 16 of krung go'i bod rig pa/（rgya yig ）
      total_pages: 182
      order: 16
      base_file: 9DD1.txt
    DD73:
      image_group_id: I4PD4172
      title: Volume 17 of krung go'i bod rig pa/（rgya yig ）
      total_pages: 198
      order: 17
      base_file: DD73.txt
    65AC:
      image_group_id: I4PD4173
      title: Volume 18 of krung go'i bod rig pa/（rgya yig ）
      total_pages: 266
      order: 18
      base_file: 65AC.txt
    AF12:
      image_group_id: I4PD4174
      title: Volume 19 of krung go'i bod rig pa/（rgya yig ）
      total_pages: 194
      order: 19
      base_file: AF12.txt
    5C9C:
      image_group_id: I4PD4175
      title: Volume 20 of krung go'i bod rig pa/（rgya yig ）
      total_pages: 166
      order: 20
      base_file: 5C9C.txt
    44D0:
      image_group_id: I4PD4176
      title: Volume 21 of krung go'i bod rig pa/（rgya yig ）
      total_pages: 208
      order: 21
      base_file: 44D0.txt
    4DE0:
      image_group_id: I4PD4177
      title: Volume 22 of krung go'i bod rig pa/（rgya yig ）
      total_pages: 264
      order: 22
      base_file: 4DE0.txt
    3A93:
      image_group_id: I4PD4178
      title: Volume 23 of krung go'i bod rig pa/（rgya yig ）
      total_pages: 226
      order: 23
      base_file: 3A93.txt
    '4628':
      image_group_id: I4PD4179
      title: Volume 24 of krung go'i bod rig pa/（rgya yig ）
      total_pages: 206
      order: 24
      base_file: 4628.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
